- name: Configuration snapshot
  hosts: homelab
  remote_user: root

  tasks:
    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "/root/config-snaphots/{{ item.name }}/"
        remote_src: true
        backup: true
        mode: "preserve"
      with_items:
        - name: vault
          path: "/etc/vault.d/"
        - name: nomad
          path: "/etc/nomad.d/"
        - name: headscale
          path: "/etc/headscale/"
        - name: consul
          path: "/etc/consul.d/"
